<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>iNeedToBuy.XYZ. Your smart shopping list.</title>
        <link href="//fonts.googleapis.com/css?family=Lato:100" rel="stylesheet" type="text/css">
        <style>
        body {
            background: white;
            color: gray;
            margin: 33vh 0 0 0;
            padding: 0;
            text-align: center;
        }

        h1 {
            color: black;
            letter-spacing: -3px;
            font: 100 84px/1.5 "Lato", "Helvetica Neue", Helvetica, Arial, sans-serif;
            margin-bottom: 0;
        }
        p {
            font: 200 18px/1.5 "Helvetica Neue", Helvetica, Arial, sans-serif;
        }
        .badge {
            background: #2185D0;
            border-radius: 0.5em;
            color: white;
            display: inline-block;
            padding: 1em 2em;
            text-decoration: none;
        }
            .badge:hover {
                text-decoration: underline;
            }
        </style>
    </head>
    <body>
        <h1>iNeedToBuy.XYZ</h1>
        <p>Your smart shopping list.</p>
        <p><a class="badge" href="&#109;&#97;&#105;&#108;&#116;&#111;&#58;&#104;&#101;&#108;&#108;&#111;&#64;&#105;&#110;&#101;&#101;&#100;&#116;&#111;&#98;&#117;&#121;&#46;&#120;&#121;&#122;&#63;&#115;&#117;&#98;&#106;&#101;&#99;&#116;&#61;&#98;&#101;&#116;&#97;&#43;&#97;&#99;&#99;&#101;&#115;&#115;&#33;">Coming Soon</a></p>
    </body>
</html>
